### ISSUE TITLE
Nodes connecting to themselves.. 

### ISSUE THREAD

**Issue by h1z1** [syncthing/relaysrv#36] opened 2016-03-08 17:57 UTC
I don't know if this is the right place to ask but to those who do run relay servers, have you noticed an increase in the number of nodes connecting back to themselves but through you?    Is there any framework already in place or being worked on to detect and protect bad behaviour?

Bit of background I was bored the other day, installed a relay for kicks.  It's running and public, mostly wanted to stress the infrastructure around it a bit.   BitTorrent was an option but DHT tends to attract a lot of attention from "researchers".  Plus, it's something I wanted to look at again anyway.

After the initial blast of nodes trying to connect I noticed a lot of relaying was actually hosts connecting back to themselves - and at great distances.   There are a large number of nodes in Brazil and China for example.  Given the server is in North America, that would seem to be either NAT hole punching fails somewhere, or really bad local administration.   The hosts in China didn't fair too well either, in the end I blocked them after pegging the node at ~60Mbit/s for 30 min..

Three hosts were also responsible for 90% of the initial connect load.  They kept connecting and disconnecting without exchanging anything.  Console output is quite verbose and useless but they were causing _thousands_ of lines like:

Listener failed to accept connection from <redacted> . Possibly a TCP Ping.

 I don't so much care about the bandwidth, guess I'm more surprised at how badly it was being used and expected to see more mobiles or something.  There are even nodes at major universities that appear unable to reach each other locally.  They topped out at 130Mbit symmetrically.. (260 total)

**Comment by AudriusButkevicius** [comment] 2016-03-08 18:30
The TCP ping implies a tcp handshake which never materialized, which is essentially a port scan, or a latency check by a potential future relay user.

The only case of nodes connecting to themselves (in terms of device ID) that is genuine is relaypoolsrv, but that should only happen one an hour or so.

How do you know that nodes were connecting to themselves though? By checking IPs? IPs are not a good metric, as it's perfectly valid for some students to be behind the same gateway yet fail local discovery and UPnP as these are simply killed by the university. If you see a lot of devices connecting to themselves in terms of ID's then I guess we have some form of abuse here .

Given we don't have any relays in Asia or South America, it's possible that you were picked as the closest target (in terms of latency).

**Comment by h1z1** [comment] 2016-03-08 23:02
Hm.   The TCP messages coincide with full connections (I can see them established and torn down).  Not sure what a latency check is tbh.   If that is something nodes do when they first contact a new relay, it would explain the massive surge of initial attempts.   The issue with them is a handful of nodes were constantly retrying more then they should.   What is kind of baffling is the connections were established anyway.  OS handled it, but app didn't maybe?

Regarding nodes connecting to themselves - completely agree assuming the nodeid's are different.  At this point I don't recall if any were or not.  I'd imagine the end users experience would be greatly enhanced if they kept that traffic as local as possible :)

From an operations perspective there is very little built in it seems to thwart abuse.  The operating system obviously has the ability, could make things worse too.

**Comment by AudriusButkevicius** [comment] 2016-03-08 23:20
Yeah, full as in, syn-synack-ack, but no data frames, so it would still show up.

All clients when they start up probe how long it takes to set up a tcp connection (mod 50 milliseconds putting them in different buckets/increments), to be able to get a feeling of how far the relay is, and tears it down immediately.
Then they keep picking a random relay from the smallest 50ms increment (or moving to next increment) until they succeed connecting to a relay.

Connections to a relay happen always regardless, because you never know if you can be reached directly. Yet if two peers are able to connect directly, they will do so, and kill their session on the relay.

Relays themselves have some sanity limits, for example if the relay starts approaching maximum FD limit, it starts disconnecting peers which have no active sessions, this way making space for others to join who might need a relay, and at the same time spreading the load a bit (as the client will go to the next relay in the list).

But yes, there are no mechanisms to prevent anything else than syncthing to use the relay, nor do I think there ever was an intention to do so.

**Comment by h1z1** [comment] 2016-03-09 02:22
Tweaking the ack time of a syn would be an interesting knob if you use that internally.   I tweaked the rttvar for now.  

What appears to be happening perhaps then is the backoff doesn't always work?    Is there any reason not to let the OS handle it?  Noting should be considered interactive here I don't think.  Even a 10 second reply isn't necessarily bad.  What I'd be worried about running Syncthing on a phone or laptop is entirely too much chatter.  Networks were built to withstand breaks in connectivity and buffer appropriately.  There is the security aspect as well.

Just a idea but think of it this way, you're at park.  Besides deploying infrastructure you also setup basic services, one of them is a relay server.   Devices roam between sites, the last thing you want is people killing their batteries pointlessly reconnecting because they're in a deadzone..

**Comment by AudriusButkevicius** [comment] 2016-03-09 08:21
Not sure what you are ralking about, we use plain TCP sockets, there is no magic involved to make the OS behave differently.

Connection failures to a relay are handled with an exponential back off, so if it fails often within a short period of time, it will increase the gaps between retrying.


Anyway, because I do not think this ticket is actionable, I am closing it.

**Closed by AudriusButkevicius** 2016-03-09 08:21 UTC

**Comment by h1z1** [comment] 2016-03-09 08:53
I'm saying the backoff didn't happen dude.  I have the logs to prove it.

I'm saying there were an unusual number of nodes connecting essentially to themselves - yes likely different instances.

The relay as it exists now does nothing to mitigate either.

**Comment by AudriusButkevicius** [comment] 2016-03-09 09:20
So you have logs of something that is the receiving side of things , so claiming that the sending side does not work by looking at receiving side is not the best thing to do.

It's possible something on the sending side started a farm of syncthings behind the same gateway, or a port scan which tries to probe/brute force something.

Until you can provide evidence of this happening and being caused by a single syncthing, I don't think it's a meaningful report, as internet is full of crazy things, and we cannot blindly blame syncthing for everything out there, just because the service is supposed to be used by syncthing.

And yes, it doesn't mitigate this as I don't see this causing actual issues, nor a way to mitigate this, as the OS will accept the connect we like it or not. Only after it was accepted we can choose to drop it, which takes us to where we already are.
